drop table if exists payment cascade;
CREATE TABLE payment (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);


drop table if exists storage_request cascade;
create table storage_request (
                                 id bigint generated by default as identity PRIMARY KEY
);

drop table if exists storage cascade;
create table storage (
                         id bigint generated by default as identity PRIMARY KEY
);

drop table if exists users cascade;
create table users (
                       id bigint generated by default as identity PRIMARY KEY
);