name: GitHub Actions 실행시켜보기

on:
  push:
    branches:
      - main
jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Hello World 찍기
        run: echo "Hello Mtak"
      - name: 폴더 만들어보기
        run: |
          mkdir test
          cd test
          echo "Hello M" > hello.txt
          cat hello.txt
          
